version: '3.7'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  mysql:
    image: mysql:8
    environment:
      # Required if username is not root
      # MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "${MSSQL_PORT}:${MSSQL_PORT}"
  sqlite:
    image: linuxserver/sqlitebrowser
    volumes:
      - ./data:/config/sqlite
    ports:
      - "${SQLITE_PORT}:${SQLITE_PORT}"
  mariadb:
    image: mariadb:10.5
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"
  oracle:
    image: container-registry.oracle.com/database/express:latest
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}
      ORACLE_ALLOW_REMOTE: true
    ports:
      - "3561:3561"
      - "${ORACLE_PORT}:${ORACLE_PORT}"
    volumes:
      - ./data:/u01/app/oracle/oradata/XE
      - ./scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 3g
          cpus: "2"
  jet-db:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash ./scripts/wait-connection.sh;'
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"
    depends_on:
      - postgres
      - mysql
      - mssql
      - sqlite
      - mariadb
      - oracle
